version: "3.9"

services:
  client_web:
    build:
      context: ./front
      dockerfile: Dockerfile.browser
    depends_on:
      - client_mobile
      - server
    ports:
      - "8081:8081"
    command: npm start
    volumes:
      - apk:/mobile_app/

  client_mobile:
    build:
      context: ./front
      dockerfile: Dockerfile.android
    volumes:
      - apk:/mobile_app/

  db:
    image: "postgres:10-alpine"
    volumes:
      - "db:/var/lib/postgresql/data"
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: redis:4.0-alpine
    command: redis-server
    ports:
      - 6379
    volumes:
      - "redis:/data"

  server:
    depends_on:
      - db
      - redis
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=db
    volumes:
      - ./backend/:/rails-app
      - bundle:/bundle

volumes:
  redis:
  db:
  apk:
  bundle:
