version: "3.9"

services:
  client_web:
    container_name: client_web
    build:
      context: ./front
      dockerfile: Dockerfile.browser
    depends_on:
      - client_mobile
    ports:
      - "8081:8081"
    command: npm start
    volumes:
      - apk:/mobile_app/

  client_mobile:
    container_name: front-android
    build:
      context: ./front
      dockerfile: Dockerfile.android
    volumes:
      - apk:/mobile_app/

volumes:
  apk: