version: "3.9"
services:
  db:
    image: "postgres:10-alpine"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: redis:4.0-alpine
    command: redis-server
    ports:
      - 6379
    volumes:
      - "redis:/data"

  web:
    depends_on:
      - "db"
      - "redis"
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db

volumes:
  redis:
  postgres:
